### ISSUE TITLE
#Question: How to load the 3D models from Scenes folder?

### ISSUE THREAD

**Issue by bipul-mohanto** [lingqiz/CSE-168x-OptiX#1]
Hi!

I have cloned your repository and trying to see a path-traced model. However, I could not define the models and getting the message `Missing path to a scene file as the first argument.`. If you do not mind telling where and how I can give the `Scenes` folder and the model path in the code?

P.S. What is the 3D model extension `test`? I, so far know `.obj` or `.py`, but did not find anything about the `.test` extension.

**Comment by lingqiz** [comment]
Hi there,

Please see the instruction in the install txt file. An example for running the program after compilation would be:  
`$ build/bin/OptiXRenderer Scenes/hw1/scene1.test `

The scene file format used here is only for this specific course (CSE-167/168). It's simply a text file with things like coordinates for the vertex, the camera direction, and parameters for the material model. 

Hope this helps!

**Comment by bipul-mohanto** [comment]
Thank you very much, it is working fine now. However, when I am trying to reading `.obj` file it is showing `Memory allocation failed (Details: Function "_rtContextLaunch2D" caught exception: Out of memory)`. Is your project specifically designed for `.test` files only?

**Comment by lingqiz** [comment]
@bipul-mohanto That's correct. The scene loader only works with the .test file format. The Renderer class then passes on the information to the ray trace program based on the OptiX interface.

**Comment by bipul-mohanto** [comment]
@lingqiz , one more thing if you do not mind. The code does not have a real-time viewer, right? I meant, after each final rendering pass, the output image is being saved as `.png` format, without any real-time visible interaction.

**Comment by lingqiz** [comment]
@bipul-mohanto That's right. As you pointed out, the code simply outputs an image file for each rendering.
